BEGIN {
    print "// Code generated by \"make -C .. object/relt.go\"; DO NOT EDIT."
    print ""
    print "package object"
    print ""
    print "var ("
    print "\tRelocationTable = map[uint64][2]string{"
}

{
    addr = "0x" toupper($1)
    kind = $2
    name = $3

    printf "\t\t%s: {\"%s\", \"%s\"},\n", addr, kind, name
}

END {
    print "\t}"
    print ")"
}
