// Code generated by "make -C .. object/relt.go"; DO NOT EDIT.

package object

var (
	RelocationTable = map[uint64][2]string{
		0x000000000000049C: {"X86_64_RELOC_BRANCH", "_realloc"},
		0x000000000000047B: {"X86_64_RELOC_BRANCH", "_malloc_good_size"},
		0x000000000000046F: {"X86_64_RELOC_BRANCH", "_malloc"},
		0x000000000000045D: {"X86_64_RELOC_BRANCH", "_memcpy"},
		0x0000000000000445: {"X86_64_RELOC_BRANCH", "_malloc"},
		0x0000000000000435: {"X86_64_RELOC_BRANCH", "_malloc_size"},
		0x000000000000031E: {"X86_64_RELOC_BRANCH", "_malloc_good_size"},
		0x00000000000002CE: {"X86_64_RELOC_BRANCH", "_abort"},
		0x00000000000002C5: {"X86_64_RELOC_BRANCH", "_abort"},
		0x00000000000002B8: {"X86_64_RELOC_SIGNED", "_malloc.heap_tail"},
		0x00000000000002AE: {"X86_64_RELOC_SIGNED", "_malloc.heap_tail"},
		0x00000000000002A4: {"X86_64_RELOC_SIGNED", "_malloc.heap_tail"},
		0x0000000000000298: {"X86_64_RELOC_SIGNED", "_malloc.heap_size"},
		0x0000000000000291: {"X86_64_RELOC_SIGNED", "_malloc.heap_head"},
		0x0000000000000284: {"X86_64_RELOC_SIGNED", "_malloc.heap_tail"},
		0x000000000000027D: {"X86_64_RELOC_BRANCH", "_malloc_good_size"},
		0x0000000000000272: {"X86_64_RELOC_BRANCH", "_malloc_good_size"},
		0x000000000000025E: {"X86_64_RELOC_BRANCH", "_malloc"},
		0x0000000000000240: {"X86_64_RELOC_BRANCH", "_abort"},
		0x00000000000001AD: {"X86_64_RELOC_SIGNED", "_IOIteratorNext.o"},
		0x00000000000001A5: {"X86_64_RELOC_SIGNED", "_IOIteratorNext.o"},
	}
)
