BEGIN {
    print "// Code generated by \"make -C .. object/secb.go\"; DO NOT EDIT."
    print ""
    print "package object"
    print ""
    print "var ("
    print "\tSectionBytes = map[string][]byte{"
}

FNR == 1 {
    BEGINFILE = 1
}

FNR != 1 {
    BEGINFILE = 0
}

BEGINFILE {
    sprintf("wc -l '%s'", FILENAME) | getline eof
    eof += 0

    key = FILENAME
    sub(/^[^.]+\./, "", key)

    printf "\t\t\"%s\": {\n", key
}

{
    printf "\t\t\t0x%s,", toupper($2)

    for (i = 3; i < 18; ++i) {
        if ($i != "") {
            printf " 0x%s,", toupper($i)
        }
    }

    printf "\n"
}

FNR == eof {
    ENDFILE = 1
}

FNR != eof {
    ENDFILE = 0
}

ENDFILE {
    printf "\t\t},\n"
}

END {
    print "\t}"
    print ")"
}
