// Code generated by "make -C .. object/sech.go"; DO NOT EDIT.

package object

var (
	SectionHeaders = map[string][2]uint64{
		"__TEXT,__text":      {0x0000000000000000, 0x000015ED},
		"__DATA,__literal16": {0x00000000000015F0, 0x00000120},
		"__DATA,__bss":       {0x0000000000001730, 0x00000060},
		"__DATA,__const":     {0x0000000000001710, 0x0000001C},
	}
)
