// Code generated by "make -C .. object/sech.go"; DO NOT EDIT.

package object

var (
	SectionHeaders = map[string][2]uint64{
		"__TEXT,__text":  {0x0000000000000000, 0x00000507},
		"__DATA,__bss":   {0x0000000000000520, 0x00000020},
		"__DATA,__const": {0x0000000000000508, 0x00000014},
	}
)
