// Code generated by "make -C .. object/sech.go"; DO NOT EDIT.

package object

var (
	SectionHeaders = map[string][2]uint64{
		"__TEXT,__text":        {0x0000000000000000, 0x00001010},
		"__DATA,__literal16":   {0x0000000000001010, 0x00000120},
		"__DATA,__bss":         {0x0000000000001148, 0x00000020},
		"__DATA,__const":       {0x0000000000001130, 0x00000014},
	}
)
