BEGIN {
    print "// Code generated by \"make -C .. object/sech.go\"; DO NOT EDIT."
    print ""
    print "package object"
    print ""
    print "var ("
    print "\tSectionHeaders = map[string][2]uint64{"
}

{
    seg = $5
    sec = $2

    key = "__" seg "," sec
    sub(/^__BSS,/, "__DATA,", key)

    pad = 21 - length(key)
    pad = sprintf("%-" pad "s", "")

    addr = "0x" toupper($4)
    size = "0x" toupper($3)

    printf "\t\t\"%s\":%s{%s, %s},\n", key, pad, addr, size
}

END {
    print "\t}"
    print ")"
}
