BEGIN {
    print "// Code generated by \"make -C .. object/symt.go\"; DO NOT EDIT."
    print ""
    print "package object"
    print ""
    print "var ("
    print "\tSymbolTable = map[string]uint64{"
}

{
    name = $3

    pad = 35 - length(name)
    pad = sprintf("%-" pad "s", "")

    addr = "0x" toupper($1)

    printf "\t\t\"%s\":%s%s,\n", name, pad, addr
}

END {
    print "\t}"
    print ")"
}
