name: Test
on:
  push: {}
jobs:
  pfw:
    name: Private Framework
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: make SHELL='/bin/bash' 'sapsigner-pfw.out'
      - run: make SHELL='/bin/bash' 'test(impl/pfw/sapsigner.out)'
  emu:
    name: Emulation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            deps: make -C impl/emu SHELL='/bin/bash' include/unicorn/unicorn.h lib/libunicorn.a
          - os: macos-15
            deps: brew install 'unicorn'
          - os: ubuntu-24.04
            deps: sudo apt-get update && sudo apt-get install -y 'libcurl4-openssl-dev' 'libsasl2-dev' && make -C 'impl/emu' SHELL='/bin/bash' 'include/unicorn/unicorn.h' 'lib/libunicorn.a'
          - os: ubuntu-24.04
            deps: sudo apt-get update && sudo apt-get install -y 'libcurl4-openssl-dev' 'libsasl2-dev' 'libunicorn-dev'
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          check-latest: true
          go-version: '~1.23'
      - uses: actions/checkout@v4
      - run: ${{ matrix.deps }}
      - run: make SHELL='/bin/bash' 'sapsigner-emu.out'
      - run: make SHELL='/bin/bash' 'test(impl/emu/sapsigner.out)'
  docker:
    name: Docker
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: make SHELL='/bin/bash' 'docker'
      - run: make SHELL='/bin/bash' 'test(hack/docker-run.sh)'
